name: 'WebExtBuild'
description: 'Build the web extension'

on: [push]




jobs:
  build:

    runs:
      using: 'docker'
      image: 'Dockerfile'

    steps:
    - name: Build the web extension
      run: 
        web-ext build
